services:
    _defaults:
        autoconfigure: true
        autowire: true

    InspiredMinds\ContaoWebMcpForms\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,ContaoWebMcpFormsBundle.php}
